### ISSUE TITLE
Issue with App Center for UWP apps

### ISSUE THREAD

**Issue by ale-ramirez** [dansiegel/Mobile.BuildTools#178]
Hi Dan,

I wonder if you guys have any solution for an issue that affects UWP apps at App Center.

I've got an app built with Xamarin Forms that works for iOS, Android, and UWP platforms.

To distribute it, I use the App Center, which works well for iOS and Android, but not for UWP.

Mobile.BuildTools is used the same way for the three platforms.

The Secrets or environment variables in the App Center are also set up the same way for the three platforms.

However, the build process only fails for UWP. The "secrets.json" is not generated, so an error is generated.

I tried to see this issue with the App Center support team, but they only suggested adding a script. I don't know how to do that, so I'm stuck with this issue.

I think it's an issue that the App Center team should fix, but it seems they're not willing to do it.

Please let me know.

Thank you very much.

Regards,

Alejandro

**Comment by dansiegel** [comment]
sounds like you're using version 1.x... the v2 preview should solve the issue for you as we describe the variables in the buildtools.json which is safe to check in... The problem is that Azure DevOps which backs App Center, uses a different behavior on their Windows build agents in which the to a ToUpper() on all variables... since we know what variables to look for in v2 we can work around the problem.. v1 can't.
