### ISSUE TITLE
The Helper class may be accessible in shared projects.

### ISSUE THREAD

**Issue by danieeis** [dansiegel/Mobile.BuildTools#210]
### SUMMARY

I know that in the buildtools you can put in which project the variable will fall but in the shared projects do not allow to add Mobile.BuildTools as a reference, therefore these secrets in some cases are needed in shared projects.

**Comment by dansiegel** [comment]
If I understand the root of your issue... your problem is that while you can add Mobile.BuildTools to each of the target platforms, each target project has a different root namespace thus you end up with:

- AwesomeApp.iOS.Helpers
- AwesomeApp.Android.Helpers
- etc

When what you need is something like:

- AwesomeApp.Helpers

Does that sound about right?

**Comment by danieeis** [comment]
Yes, thats right, something like AwesomeApp.Common.Helpers

Where secrets can be built from that project and be accessible to all others and for shared projects.

https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/shared-projects?tabs=macos

I believe that by marking the class as public this can be done, I am not sure if this is correct, but I also find that they are marked in red in the editor.

I create a sample app [ExampleShared](https://github.com/danieeis/ExampleShared)

**Comment by dansiegel** [comment]
this is available in the latest CI build on Sponsor Connect... you now can specify the RootNamespace that you want to use. If not specified we will use the current project's root namespace

**Comment by danieeis** [comment]
Thanks @dansiegel
