### ISSUE TITLE
Is a new version of Mobile.BuildTools still being developed?

### ISSUE THREAD

**Issue by eth-ellis** [dansiegel/Mobile.BuildTools#336]
Hey @dansiegel, in another comment you mentioned a new version of Mobile.BuildTools was being developed.

Is this still being progressed?

Is there an ETA on when this will be released?

Thanks!

**Comment by dansiegel** [comment]
Unfortunately this isn't something I have time to get to right now and nobody in the community has stepped up to help. So the answer is yes I would like to get an update out but I'm not sure when that will be exactly. I'm currently swamped between my day job and trying to get an updated release out for Prism.

**Comment by eth-ellis** [comment]
Understood. Thanks for the update @dansiegel.

Any thoughts on how issue #330 could be fixed?

App settings work out of the box with .NET MAUI which is great!
But the tokenised manifest tasks don't seem to be running.
Not getting any error messages in the build output either.

**Comment by dansiegel** [comment]
The break is most likely due to the fact that they changed something with the targets from Android/iOS. It's not something I have the time to look at any time soon. I'm happy to help guide someone from the community on how to do it and get that merged so we can actually try to get a build out but I'm swamped with work atm.
