### ISSUE TITLE
Add support to secrets.json of arrays of primitives

### ISSUE THREAD

**Issue by RomaRudyak** [dansiegel/Mobile.BuildTools#46]
### SUMMARY

As a consumer of Mobile.BuildTools I want to have possibility to add to secrets.json array of primitives. 

### DETAILS

Example of secrets.json:
```json
{

    "Scopes": [
         "Scope1Defenition",
         "Scope@Defenition"
   ]
}
```

Example of Consumption:
```csharp

string[] scopes = Secrets.Scopes;

```

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by dansiegel** [comment]
At a high level I'm not opposed to this. However the Secrets need to work easily in a CI Environment. Currently I would handle this where I might have:

```json
{
  "Scope1": "someValue",
  "Scope2": "anotherValue"
}
```

Where I then have a Constants class like:

```cs
public static class AppConstants
{
    public static string[] Scopes => new string[] { Secrets.Scope1, Secrets.Scope2 };
}
```

Naturally the problem is that this assumes you always have a predefined number of scopes. Have you considered how you handle this in a CI Environment where the secrets.json needs to generate dynamically?

**Comment by RomaRudyak** [comment]
@dansiegel thank you for quick reply.

Environment array represented as string with known separator.
 - On Unix this is `:`
 - On Windows this is `;`

We can make it be like this:
```bash
# Bash
export $Default_Scopes="Scope1:Scope2"
```
```cmd
:: Windows
set Default_Scopes="Scope1;Scope2"
```

And generated secrets.json:
```json
{

    "Scopes": [
         "Scope1",
         "Scope2"
   ]
}
```
