### ISSUE TITLE
Two netstandard projects with secret.json

### ISSUE THREAD

**Issue by soydachi** [dansiegel/Mobile.BuildTools#55]
# Description

I have two netstandard projects like MyProject.Core and MyProject. In both is installed Mobile.BuildTools and both have the secrects.json file added with his corresponding variables.

In local it's working fine but when I'm send a build in azure pipeline, only the first project get the variables working. 

## Reproduction Steps

1. Create Xamarin.Forms project and add an additional net standard 2.0 project that depends on the PCL.
2. Install Moblie.BuildTools in both PCL projects and add secrets.json file.
3. In both csproj add <BuildHostSecretPrefix>SAFE_</BuildHostSecretPrefix> in a PropertyGroup
4. Create an Azure Pipeline with this variables and queue this build.
5. You will see that first PCL works but the second don't catch the variables.

## Expected Behavior

Create in both PCL the Secrets.cs with the values of this variables.

## Actual Behavior

Create in both PCL the Secrets.cs without the values of this variables.

## Environment

- OS: [OSX]
- IDE: [VSMac]
- BuildTools Version: [1.4.0.638]
- IDE Version: [7.7.3 (build 43)]
- Build Target Framework: [netstandard2.0]

## Reproduction App

No included an repo.

**Comment by dansiegel** [comment]
Closing as there is no sample included for me to see what your exact problem is... Keep in mind a sample doesn't need to be a full blown solution just something to demonstrate the issue you're experiencing.

Since you're good locally and it's failing in Azure Pipelines I would also need to know what build host you're using. I see you're using Mac locally but are you building on a Mac or Windows agent?
