### ISSUE TITLE
How to customise Secrets.cs?

### ISSUE THREAD

**Issue by AdamDiament** [dansiegel/Mobile.BuildTools#81]
Hi Dan, sorry to raise this as a bug but how do I customise the name / location / namespace of the Secrets.cs file? The documentation mentions this being possible in version 2 but there're no instructions I can find, and the latest nuget is 1.4 something.

Thanks!

**Comment by AdamDiament** [comment]
Also is there a way to make the generated Secrets.cs class public instead of internal so that I can reference it in another class library?

**Comment by dansiegel** [comment]
@AdamDiament yeah I've been in the middle of a major update for Mobile.BuildTools to 2.0 and have been trying to get things updated ahead of time here. As for your last question is not possible to change the visibility from internal to public, however you can add:

```cs
[assembly: InternalsVisibleTo("SomeOtherAssembly")]
```

and the Secrets class would then be visible to that other assembly. I've sometimes done this when adding secrets to my net standard project where I need access to something from one of the platform heads.

As for your first questions there those should be able to be controlled to a degree by adding some properties to the csproj of your project:

```xml
<PropertyGroup>
  <SecretsClassName>AwesomAppSettings</SecretsClassName>
  <SecretsOutputPath>$(MSBuildProjectDirectory)Config</SecretsOutputPath>
</PropertyGroup>
```

To be honest I never used this feature, however this should generate a class called AwesomeAppSettings in the Config namespace of your project instead of the Helpers namespace.
